### ISSUE TITLE
运行demo出现此错误.设备三星S8.点击打开相册就闪退了

### ISSUE THREAD

**Issue by yuwoquan** [NFLeo/Matisse-Kotlin#16]
E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.leo.matisse, PID: 24564
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: mimeType must not be null
        at com.matisse.loader.AlbumLoader.getUri(AlbumLoader.kt:216)
        at com.matisse.loader.AlbumLoader.loadBelowAndroidQ(AlbumLoader.kt:124)
        at com.matisse.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:108)
        at com.matisse.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:21)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by NFLeo** [comment]
你的设备是安卓10吧  安卓10一直没真正去试过

**Comment by yuwoquan** [comment]
Android 9 而已，而且我用小米5s也会这样子

**Comment by NFLeo** [comment]
demo比较粗糙，可能是你那里 列数量和列宽度这两个值没设置好。我已经提交代码了，更新到了2.0.2

**Comment by yuwoquan** [comment]
thanks
