### ISSUE TITLE
开启裁剪，打开相机拍照，确认之后闪退

### ISSUE THREAD

**Issue by beanu** [NFLeo/Matisse-Kotlin#25]
下载了最新的源码v2.1 ，并运行在华为手机。
开启裁剪功能，然后打开相机拍照，然后点击右上角确认，闪退。

错误信息

`  Caused by: android.database.CursorIndexOutOfBoundsException: Requested column: -1, # of columns: 0
        at android.database.MatrixCursor.get(MatrixCursor.java:66)
        at android.database.MatrixCursor.getString(MatrixCursor.java:254)
        at android.database.CursorWrapper.getString(CursorWrapper.java:137)
        at com.matisse.utils.PhotoMetadataUtils.getPath(PhotoMetadataUtils.kt:47)
        at com.matisse.utils.IntentUtils.startCrop(IntentUtils.kt:36)
        at com.matisse.utils.IntentUtils.gotoImageCrop(IntentUtils.kt:22)
        at com.leo.matisse.ExampleActivity.doActivityResultForCapture(ExampleActivity.kt:370)
        at com.leo.matisse.ExampleActivity.onActivityResult(ExampleActivity.kt:348)
        at android.app.Activity.dispatchActivityResult(Activity.java:7797)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
`

**Comment by NFLeo** [comment]
你的设备是不是Android Q？  10的适配还是有问题

**Comment by NFLeo** [comment]
刚提交了你可以试下  我这里借的华为是没问题。不知道你那边怎么样

**Comment by beanu** [comment]
是的，还是会闪退。这次的错误信息是
`Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
        at com.matisse.utils.PathUtils.getDataColumn(PathUtils.kt:96)
        at com.matisse.utils.PathUtils.getPath(PathUtils.kt:66)
        at com.matisse.utils.IntentUtils.startCrop(IntentUtils.kt:37)
        at com.matisse.utils.IntentUtils.gotoImageCrop(IntentUtils.kt:23)
        at com.leo.matisse.ExampleActivity.doActivityResultForCapture(ExampleActivity.kt:370)
        at com.leo.matisse.ExampleActivity.onActivityResult(ExampleActivity.kt:348)
        at android.app.Activity.dispatchActivityResult(Activity.java:7797)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)`

机型：华为 JKM-AL00b, 华为Mate 9

**Comment by NFLeo** [comment]
刚刚上传了，麻烦再用你的机子帮我试一下。

**Comment by beanu** [comment]
可以拍照剪切了，但是剪切完点击“确认”之后，返回到前一个页面没有结果。我debug看一下哪里出了问题。

**Comment by NFLeo** [comment]
好的  你对照一下demo，看看拿不同值的获取方法

**Comment by beanu** [comment]
`UCrop.of(originalPath, Uri.fromFile(file))
        .withAspectRatio(1f, 1f)
        .withOptions(options)
        .start(activity)`

start中使用的REQUEST_CROP=69

而我们的ExampleActivity中的REQUEST_CODE_CROP=25 ，两个不一致。拍照剪切返回到ExampleActivity的onActivityResult中requestCode=69

**Comment by NFLeo** [comment]
哦哦 对 确实有这个问题，老的裁剪key还没删，我处理下再发布下

**Comment by beanu** [comment]
在ExampleActivity的onActivityResult中增加以下代码
`UCrop.REQUEST_CROP -> {
                data?.run {
                    val resultUri = UCrop.getOutput(data)
                    resultUri?.let { showCompressedPath(it) }
                }
            }`

另外不知道为什么拍照裁剪会卡一会，选择照片裁剪会很快。

**Comment by NFLeo** [comment]
两处裁剪都是耗时的，可能是拍照的图会大些，耗时更长。后续打算加loading给个交互提示的，这期bug太多来不及
