### ISSUE TITLE
UCropActivity getStatusBarFuture is null

### ISSUE THREAD

**Issue by zhyricky** [NFLeo/Matisse-Kotlin#29]
Vivo R9m API 21

CrashLog:

java.lang.RuntimeException: Unable to start activity ComponentInfo{XXXXX/com.matisse.ucrop.UCropActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.jvm.functions.Function2.invoke(java.lang.Object, java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5958)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.jvm.functions.Function2.invoke(java.lang.Object, java.lang.Object)' on a null object reference
        at com.matisse.ucrop.UCropActivity.configActivity(UCropActivity.java:71)
        at com.matisse.ui.activity.BaseActivity.onCreate(BaseActivity.kt:26)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)

**Comment by LingsGroup** [comment]
你解决了吗，我也遇到这个问题

**Comment by HaleLiu** [comment]
同样问题

**Comment by PontonMao** [comment]
add this code at Matisse.from(this)...

.setStatusBarFuture { params, view ->
}
