### ISSUE TITLE
minsdk最小19么？引用编译后直接崩溃，报错如下

### ISSUE THREAD

**Issue by xukun6868668** [NFLeo/Matisse-Kotlin#8]
说你的MatisseActivity，notFountException，问你是否在manifest注册，什么鬼？

**Comment by NFLeo** [comment]
demo能跑起来吗？对比看看是不是少了什么

**Comment by xukun6868668** [comment]
Process: com.inno.wework, PID: 14788
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.inno.wework/com.matisse.ui.view.MatisseActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class TextView
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0402ce a=-1}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:771)
        at android.widget.TextView.<init>(TextView.java:1303)
        at android.widget.TextView.<init>(TextView.java:872)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1006)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.matisse.ui.view.MatisseActivity.onCreate(MatisseActivity.kt:83)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
2019-10-11 15:07:30.523 710-2714/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.

**Comment by xukun6868668** [comment]
这个我知道了，是设置them的问题。还有一个问题是设置了选择图片的个数，选择满的时候点击另外一个图片怎么没有“最多选择几张的toast”，这样用户就没有交互体验

**Comment by NFLeo** [comment]
恩  toast是没加，最近正在改。考虑到toast样式与宿主项目不一致问题，把原先的原生toast去掉了
